import React, { Component } from 'react'

export default class Terms extends Component {

  render() {

    return (
      <div className="container post-section">
        <h2 className="p-title">TERMS & CONDITIONS</h2>
        <div className="p-content">
          <p className="p1">1. Application and Acceptance of the Terms</p>
          <p className="p2"><span className="s1">2. Users Generally</span></p>
          <p className="p2"><span className="s1">3. Member Accounts</span></p>
          <p className="p2"><span className="s1">4. Transactions Between Buyers and Sellers</span></p>
          <p className="p2"><span className="s1">5. Limitation of Liability</span></p>
          <p className="p2"><span className="s1">6. Copyright and Patents</span></p>
          <p className="p2"><span className="s1">7. Force Majeure</span></p>
          <p className="p2"><span className="s1">8. General Provisions</span></p>
          <p className="p2"><span className="s1"><b>APPLICATION AND ACCEPTANCE OF THE TERMS</b></span></p>
          <p className="p2"><span className="s1">PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY!</span></p>
          <p className="p2"><span className="s1">Welcome to www.Insta360.com! These Terms of Use describe the terms and conditions applicable to your access and use of the website at www.Insta360.com(referred to as "Site". This document is a legally binding agreement between you as the user(s) of the Site (referred to as "you", "your" or "User" hereinafter) and the Insta360.com entity listed below (referred to as "we", "our" or "Insta360.com" hereinafter).</span></p>
          <p className="p2"><span className="s1">1.Application and Acceptance of the Terms</span></p>
          <p className="p2"><span className="s1">1. Your use of the Site and Insta360.com's services, software and products (collectively the as the "Services" hereinafter) is subject to the terms and conditions contained in this document as well as the Privacy Policy and any other rules and policies of the Site that Insta360.com may publish from time to time. This document and such other rules and policies of the Site are collectively referred to below as the "Terms". By accessing the Site or using the Services, you agree to accept and be bound by the Terms. Please do not use the Services or the Site if you do not accept all of the Terms.</span></p>
          <p className="p2"><span className="s1">2. You may not use the Services and may not accept the Terms if (a) you are not of legal age to form a binding contract with Insta360.com, or (b) you are not permitted to receive any Services under the laws of P.R.China or other countries / regions including the country / region in which you are resident or from which you use the Services.</span></p>
          <p className="p2"><span className="s1">3. You acknowledge and agree that Insta360.com may amend any Terms at any time by posting the relevant amended and restated Terms on the Site. By continuing to use the Services or the Site, you agree that the amended Terms will apply to you.</span></p>
          <p className="p2"><span className="s1">4. If Insta360.com has posted or provided a translation of the English language version of the Terms, you agree that the translation is provided for convenience only and that the English language version will govern your users of the Services or the Site.</span></p>
          <p className="p2"><span className="s1">5. You may be required to enter a separate agreement, whether online or offline, with Insta360.com or our affiliate for any Service ("Additional Agreements"). If there is any conflict or inconsistency between the Terms and an Additional Agreement, the Additional Agreement shall take precedence over the Terms only in relation to that Service concerned.</span></p>
          <p className="p2"><span className="s1">6. The Terms may not otherwise be modified except in writing by an authorized officer of Insta360.com.</span></p>
          <p className="p2"><span className="s1"><b>USERS GENERALLY</b></span></p>
          <p className="p2"><span className="s1">1. As a condition of your access to and use of the Site or Services, you agree that you will comply with all applicable laws and regulations when using the Site or Services.</span></p>
          <p className="p2"><span className="s1">2. You agree to use the Site or Services solely for your own private and internal purposes. You agree that (a) you will not copy, reproduce, download, republish, sell, distribute or resell any Services or any information, text, images, graphics, video clips, sound, directories, files, databases or listings, etc. available on or through the Site (the "Site Content"), and (b) you will not copy, reproduce, download, compile or otherwise use any Site Content for the purposes of operating a business that competes with Insta360.com, or otherwise commercially exploiting the Site Content. Systematic retrieval of Site Content from the Site to create or compile, directly or indirectly, a collection, compilation, database or directory (whether through robots, spiders, automatic devices or manual processes) without written permission from Insta360.com is prohibited. Use of any content or materials on the Site for any purpose not expressly permitted in the Terms is prohibited.</span></p>
          <p className="p2"><span className="s1">3. You must read INSTA360's Privacy Policy which governs the protection and use of personal information about Users in the possession of Insta360.com and our affiliates. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy.</span></p>
          <p className="p2"><span className="s1">4. Insta360.com may allow Users to access to content, products or services offered by third parties through hyperlinks (in the form of word link, banners, channels or otherwise), API or otherwise to such third parties' website. You are cautioned to read such website' terms and conditions and/or privacy policies before using the Site. You acknowledge that Insta360.com has no control over such third parties' website, does not monitor such website, and shall not be responsible or liable to anyone for such web site, or any content, products or services made available on such website.</span></p>
          <p className="p2"><span className="s1">5. You agree not to undertake any action to undermine the integrity of the computer systems or networks of Insta360.com and / or any other User nor to gain unauthorized access to such computer systems or networks.</span></p>
          <p className="p2"><span className="s1">6. You agree not to undertake any action which may undermine the integrity of INSTA360's feedback system, such as leaving positive feedback for yourself using secondary Member IDs or through third parties or by leaving unsubstantiated negative feedback for another User.</span></p>
          <p className="p2"><span className="s1">7. By posting or displaying any information, content or material ("User Content") on the Site or providing any User Content to Insta360.com or our representative(s), you grant an irrevocable, perpetual, worldwide, royalty-free, and sub-licensable (through multiple tiers) license to Insta360.com to display, transmit, distribute, reproduce, publish, duplicate, adapt, modify, translate, create derivative works, and otherwise use any or all of the User Content in any form, media, or technology now known or not currently known in any manner and for any purpose which may be beneficial to the operation of the Site, the provision of any Services and/or the business of the User. You confirm and warrant to Insta360.com that you have all the rights, power and authority necessary to grant the above license.</span></p>
          <p className="p2"><span className="s1"><b>MEMBER ACCOUNTS</b></span></p>
          <p className="p2"><span className="s1">1. The User must be registered on the Site to access or use some Services (a registered User is also referred to as a "Member" below). Except with Insta360.com's approval, one User may only register one member account on the Site. Insta360.com may cancel or terminate a User's member account if Insta360.com has reasons to suspect that the User has concurrently registered or controlled two or more member accounts. Further, Insta360.com may reject User's application for registration for any reason.</span></p>
          <p className="p2"><span className="s1">2. Upon registration on the Site, Insta360.com shall assign an account and issue a member ID and password (the latter shall be chosen by a registered User during registration) to each registered User. An account may have a web-based email account with limited storage space for the Member to send or receive emails.</span></p>
          <p className="p2"><span className="s1">3. A set of Member ID and password is unique to a single account. Each Member shall be solely responsible for maintaining the confidentiality and security of your Member ID and password and for all activities that occur under your account. No Member may share, assign, or permit the use of your Member account, ID or password by another person outside of the Member's own business entity. Member agrees to notify Insta360.com immediately if you become aware of any unauthorized use of your password or your account or any other breach of security of your account.</span></p>
          <p className="p2"><span className="s1">4. Member agrees that all activities that occur under your account (including without limitation, posting any company or product information, clicking to accept any Additional Agreements or rules, subscribing to or making any payment for any services, sending emails using the email account or sending SMS) will be deemed to have been authorized by the Member.</span></p>
          <p className="p2"><span className="s1">5. Member acknowledges that sharing of your account with other persons, or allowing multiple users outside of your business entity to use your account (collectively, "multiple use"), may cause irreparable harm to Insta360.com or other Users of the Site. Member shall indemnify Insta360.com, our affiliates, directors, employees, agents and representatives against any loss or damages (including but not limited to loss of profits) suffered because of the multiple use of your account. Member also agrees that in case of the multiple use of your account or Member's failure to maintain the security of your account, Insta360.com shall not be liable for any loss or damages arising from such a breach and shall have the right to suspend or terminate Member's account without liability to Member.</span></p>
          <p className="p2"><span className="s1"><b>TRANSACTIONS BETWEEN BUYERS AND SELLERS</b></span></p>
          <p className="p2"><span className="s1">1. Users are hereby made aware that there may be risks of dealing with people acting under false pretenses. Insta360.com uses several techniques to verify the accuracy of certain information our paying Users provide us when they register for a paying membership service on the Site. However, because user verification on the Internet is difficult, Insta360.com cannot and does not confirm each User's purported identity (including, without limitation, paying Members). We encourage you to use various means, as well as common sense, to evaluate with whom you are dealing.</span></p>
          <p className="p2"><span className="s1">2. Each User acknowledges that it is fully assuming the risks of conducting any purchase and sale transactions in connection with using the Site or Services, and that it is fully assuming the risks of liability or harm of any kind in connection with subsequent activity of any kind relating to products or services that are the subject of transactions using the Site. Such risks shall include but are not limited to, misrepresentation of products and services, fraudulent schemes, unsatisfactory quality, failure to meet specifications, defective or dangerous products, unlawful products, delay or default in delivery or payment, cost miscalculations, breach of warranty, breach of contract and transportation accidents. Such risks also include the risks that the manufacture, importation, export, distribution, offer, display, purchase, sale and/or use of products or services offered or displayed on the Site may violate or may be asserted to violate Third Party Rights, and the risk that User may incur costs of defense or other costs in connection with third parties' assertion of Third Party Rights, or in connection with any claims by any party that they are entitled to defense or indemnification in relation to assertions of rights, demands or claims by Third Party Rights claimants. Such risks also include the risks that consumers, other purchasers, end-users of products or others claiming to have suffered injuries or harms relating to products originally obtained by Users of the Site as a result of purchase and sale transactions in connection with using the Site may suffer harms and/or assert claims arising from their use of such products. All of the foregoing risks are hereafter referred to as "Transaction Risks". Each User agrees that Insta360.com shall not be liable or responsible for any damages, claims, liabilities, costs, harms, inconveniences, business disruptions or expenditures of any kind that may arise a result of or in connection with any Transaction Risks. At last, all of the products display on Insta360.com will meet the legitimate demands of compliance.</span></p>
          <p className="p2"><span className="s1">3. User agrees to provide all information and materials as may be reasonably required by Insta360.com in connection with your transactions conducted on, through or as a result of use of the Site or Services. Insta360.com has the right to suspend or terminate any User's account if the User fails to provide the required information and materials.</span></p>
          <p className="p2"><span className="s1"><b>LIMITATION OF LIABILITY</b></span></p>
          <p className="p2"><span className="s1">1. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICES PROVIDED BY INSTA360.COM ON OR THROUGH THE SITES ARE PROVIDED "AS-IS", "AS AVAILABLE" AND "WITH ALL FAULTS", AND INSTA360.COM HEREBY EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, ANY WARRANTIES OF CONDITION, QUALITY, DURABILITY, PERFORMANCE, ACCURACY, RELIABILITY, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. ALL SUCH WARRANTIES, REPRESENTATIONS, CONDITIONS, AND UNDERTAKINGS ARE HEREBY EXCLUDED.</span></p>
          <p className="p2"><span className="s1">2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, INSTA360.COM MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE VALIDITY, ACCURACY, CORRECTNESS, RELIABILITY, QUALITY, STABILITY, COMPLETENESS OR CURRENTNESS OF ANY INFORMATION PROVIDED ON OR THROUGH THE SITES; INSTA360.COM DOES NOT REPRESENT OR WARRANT THAT THE MANUFACTURE, IMPORTATION, EXPORT, DISTRIBUTION, OFFER, DISPLAY, PURCHASE, SALE AND/OR USE OF PRODUCTS OR SERVICES OFFERED OR DISPLAYED ON THE SITES DOES NOT VIOLATE ANY THIRD PARTY RIGHTS; AND INSTA360.COM MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND CONCERNING ANY PRODUCT OR SERVICE OFFERED OR DISPLAYED ON THE SITES.</span></p>
          <p className="p2"><span className="s1">3. Any material downloaded or otherwise obtained through the Site is done at each User's sole discretion, and risk and each User is solely responsible for any damage to INSTA360's computer system or loss of data that may result from the download of any such material. No advice or information, whether oral or written, obtained by any User from Insta360.com or through or from the Site shall create any warranty not expressly stated herein.</span></p>
          <p className="p2"><span className="s1">4. Each User hereby agrees to indemnify and save Insta360.com, our affiliates, directors, officers and employees harmless, from any and all losses, claims, liabilities (including legal costs on a full indemnity basis) which may arise from such User's use of the Site or Services (including but not limited to the display of such User's information on the Site) or from your breach of any of the terms and conditions of the Terms. Each User hereby further agrees to indemnify and save Insta360.com, our affiliates, directors, officers and employees harmless, from any and all losses, damages, claims, liabilities (including legal costs on a full indemnity basis) which may arise from User's breach of any representations and warranties made by User to Insta360.com, including but not limited to those set forth in Section 5 hereunder.</span></p>
          <p className="p2"><span className="s1">5. Each User hereby further agrees to indemnify and save Insta360.com, our affiliates, directors, officers and employees harmless, from any and all losses, damages, claims, liabilities (including legal costs on a full indemnity basis) which may arise, directly or indirectly, as a result of any claims asserted by Third Party Rights claimants or other third parties relating to products offered or displayed on the Site. Each User hereby further agrees that Insta360.com is not responsible and shall have no liability to you, for any material posted by others; including defamatory, offensive or illicit material and that the risk of damages from such material rests entirely with each User. Insta360.com reserves the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you shall cooperate with Insta360.com in asserting any available defenses.</span></p>
          <p className="p2"><span className="s1">6. Insta360.com shall not be liable for any special, direct, indirect, punitive, incidental or consequential damages or any damages whatsoever (including but not limited to damages for loss of profits or savings, business interruption, loss of information), whether in contract, negligence, tort, equity or otherwise or any other damages resulting from any of the following.</span></p>
          <p className="p2"><span className="s1">1. the use or the inability to use the Site or Services;</span></p>
          <p className="p2"><span className="s1">2. any defect in goods, samples, data, information or services purchased or obtained from a User or any other third party through the Site;</span></p>
          <p className="p2"><span className="s1">3. unauthorized access by third parties to data or private information of any User;</span></p>
          <p className="p2"><span className="s1">4. statements or conduct of any User of the Site;</span></p>
          <p className="p2"><span className="s1">5. any matters relating to Services, however, arising, including negligence.</span></p>
          <p className="p2"><span className="s1">7. The limitations and exclusions of liability to you under the Terms shall apply to the maximum extent permitted by law and shall apply whether or not Insta360.com has been advised of or should have been aware of the possibility of any such losses arising.</span></p>
          <p className="p2"><span className="s1"><b>COPYRIGHT AND PATENTS</b></span></p>
          <p className="p2"><span className="s1">All content included on this site, such as text, graphics, logos, button icons, images, and audio clips, digital downloads, data compilations, and software, is the property of INSTA360.COM or its content suppliers and protected by international copyright laws. The use of any INSTA360.COM trademark or service mark without our express written consent is strictly prohibited.</span></p>
          <p className="p2"><span className="s1"><b>FORCE MAJEURE</b></span></p>
          <p className="p2"><span className="s1">Under no circumstances shall Insta360.com be held liable for any delay or failure or disruption of the content or services delivered through the Site resulting directly or indirectly from acts of nature, forces or causes beyond our reasonable control, including without limitation, Internet failures, computer, telecommunications or any other equipment failures, electrical power failures, strikes, labor disputes, riots, insurrections, civil disturbances, shortages of labor or materials, fires, flood, storms, explosions, acts of God, war, governmental actions, orders of domestic or foreign courts or tribunals or non-performance of third parties.</span></p>
          <p className="p2"><span className="s1"><b>GENERAL PROVISIONS</b></span></p>
          <p className="p2"><span className="s1">1. Subject to any Additional Agreements, the Terms constitute the entire agreement between you and Insta360.com</span></p>
          <p className="p2"><span className="s1"> with respect to and govern your use of the Site and Services, superseding any prior written or oral agreements in relation to the same subject matter herein.</span></p>
          <p className="p2"><span className="s1">2. Insta360.com and you are independent contractors, and no agency, partnership, joint venture, employee-employer or franchiser-franchisee relationship is intended or created by the Terms.</span></p>
          <p className="p2"><span className="s1">3. If any provision of the Terms is held to be invalid or unenforceable, such provision shall be deleted, and the remaining provisions shall remain valid and be enforced.</span></p>
          <p className="p2"><span className="s1">4. Headings are for reference purposes only and in no way define, limit, construe or describe the scope or extent of such section.</span></p>
          <p className="p2"><span className="s1">5. Insta360.com's failure to enforce any right or failure to act with respect to any breach by you under the Terms will not constitute a waiver of that right nor a waiver of Insta360.com's right to act with respect to subsequent or similar breaches.</span></p>
          <p className="p2"><span className="s1">6. Insta360.com shall have the right to assign the Terms (including all of our rights, titles, benefits, interests, and obligations and duties in the Terms to any person or entity (including any affiliates of INSTA360.COM). You may not assign, in whole or part, the Terms to any individual or entity.</span></p>
          <p className="p2"><span className="s1">7. Any dispute relating in any way to your visit to INSTA360.COM or to products or services sold or distributed by INSTA360.COM or through INSTA360.COM shall be submitted to CIETAC, South China Sub-Commission for arbitration which shall be conducted in accordance with the Commission's arbitration rules in effect at the time of applying for arbitration. The number of arbitrators shall be one; The place of arbitration shall be Shenzhen China; The language to be used in the arbitral proceedings shall be Chinese. The arbitral award is final and binding upon both you and INSTA360.</span></p>
        </div>
      </div>

    )

  }
}